name: tag_repository
description: Dart package which manages the tags domain.
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  http: ^0.13.4

